### ISSUE TITLE
Information about the v1.4 mod menu

### ISSUE THREAD

**Issue by Devilx86fan** [Devilx86/ImpostorModmenu#18]
Hello @Devilx86 What do you know about the new version?

**Comment by amongX86** [comment]
Nobody knows anything about v1.4, if you have request for features ask otherwise stop creating spam post.

**Comment by Devilx86fan** [comment]
Sorry bro

**Comment by Redlything** [comment]
He says that he added a feature thats super funny and couldnt stop laughing.Just a peak from him hahahaha

**Comment by Devilx86** [comment]
Hello 1.4 was not release publicly since among us introduced anticheat and patched some fun features I had added in the menu. There were things like:
Swap Player (Swap appreance, name and position with other player of your choice, Hillarious when you use it for stack kills, no one would believe them when the deny killing)
Swap Player on Murder
Copy Player (Also Copies their name and makes them "Name 1" so you seem like the original player)

However these result in a ban, hence I decided to not release it, I will push the source code here later tho.
