### ISSUE TITLE
Menu v1.5 feedback

### ISSUE THREAD

**Issue by smethadome** [Devilx86/ImpostorModmenu#50]
I know you haven't finished v1.5 yet due to some bugs but this is feedback on using it:-

- The max light function still doesn't work.
- You can't murder another player using the 'Murder Crew' option.
- If you change name from the mod menu it crashed the game.
- After being voted out as fake imposter, you aren't a ghost and the screen frame is frozen.
- 'Change on murder' option gets you banned.
- 'Teleport me to Murderer' doesn't work
- 'complete all tasks' still gets you banned
- 'copy player' is very temperamental.
- 'sabotage loop' doesn't work.

-'max players' is such an amazing functionality you've added but no more than 10 could join when hosting to the public, is this because only code invite is allowed after the max 10 player mark is achieved?

Thanks for your hard work and it's been fun testing everything, I'm looking forward to the final stages of this menu. 😊

**Comment by Devilx86** [comment]
Hello, Thanks your feedback is for 1.5, I have fixed some of these in 1.5.1, however some of these are still broken in 1.5.2:
- As I mentioned in the forum thread, max light is broken in 1.5.1 due to some final untested changes I made before releasing, I have fixed this in 1.5.2 will release in 2 to 3 days.
- Murder crew and Murder player works only as impostor. In order to murder as not being the impostor (like in 1.3) one needs a ban bypass exploit or an anti ban exploit.
- Name changer issues were fixed in 1.5.1 it works fine now. There is just a small bug where once your name is set it allows you to continue chatting. I have changed in 1.5.2 so that even if name is set you need to manually turn off name changer, this is to ensure you don't accidentally send messages in chat.
- After being voted out as fake imposter, you aren't a ghost and the screen frame is frozen - This is not related to fake impostor, I am not sure what causes this however this happens really rarely and the once that have reported this don't know what caused it exactly either, I have tried it with fake impostor and does not seem to cause the issue for me.

'Change on murder' option gets you banned. - This works fine for me and many others no ban, If you got banned for using this it probably has to do with some other feature. Since you said you are on 1.5 Complete player task method was banned in 1.5 however in 1.5.1 this was fixed you can complete tasks with no ban.

'Teleport me to Murderer' doesn't work - It works fine for me and many others (I have asked people to test it out) no idea why its not working for you, but let me know if you have any clue as to why its broken for you.

'complete all tasks' still gets you banned - Try 1.5.1 its fixed, you can complete tasks host/non host no ban.

'copy player' is very temperamental - Copy Player works fine, the only bug with it is. if you are host it adds a "1" to your name after copying however non host it works fine unless someone else has copied your name. As for Colors etc, you cannot steal other player color. This was a feature in 1.4 called "Swap Player". Fortunately Among Us patched it and introduced anti cheat measures to their servers before I could release.

'sabotage loop' doesn't work - I think you mean Sabotage All? In 1.5 the method from 1.3 was patched in the new client. This old method only works locally. However it was rewritten in 1.5.1 and works for all players visually. If you are talking about sabotage loop for lights, there was a bug here basically the lights auto fix itself after 2 to 3 iterations. But fixed this too in 1.5.2. Which I will release in a few days.

Max players is only visual at the moment. The Among Us official servers only allow 10 players per lobby. However adding more than 10 players is something I will be working on in the future.

**Comment by pokeyjojo** [comment]
The github still says that the mod menu is on 1.3 how is there a 1.5?

**Comment by Devilx86** [comment]
> The github still says that the mod menu is on 1.3 how is there a 1.5?

Because up to 1.3 I was regularly updating the source here. 1.4 was patched before I could release and 1.5 is out but its buggy and incomplete, I have not implemented everything yet. However you can get a copy of it from here:
https://www.youtube.com/watch?v=IrTNdvR7BeM
