### ISSUE TITLE
1.5 bug permanent darkness

### ISSUE THREAD

**Issue by Magatsu-Iz** [Devilx86/ImpostorModmenu#51]
After voting (after the game tells if the person was an imposter), the screen goes black permanently. I can still hear sounds which means im still in the game, i just cant see anything.

**Comment by Devilx86** [comment]
Thanks, There are two cases where this happens, one is common and it is due to a bug in the game. Happens with no mods on an IOS device too. The another is due to max light and no shadows. I have Fixed this in 1.5.2 will be out in 2 to 3 days with some more new features. As for source code I am delaying it a little bit to prevent Youtubers from stealing my menu like with 1.3.
