### ISSUE TITLE
Kill cooldown anticheat

### ISSUE THREAD

**Issue by RedKnight341** [Devilx86/ImpostorModmenu#55]
They now have anticheat for kill cooldown

**Comment by Devilx86** [comment]
Thanks, removed in v1.6 because Among Us has started verifying that you kill within the kill timer, hence you get banned for making multiple kills at the same time. However in 1.6, you can still use it as the the host. Set kill cool down to 1 from the menu. If you set it to 0 and you make someone else the impostor they cannot kill anyone (kept it for trolling).
