### ISSUE TITLE
close this

### ISSUE THREAD

**Issue by amongX86** [Devilx86/ImpostorModmenu#7]

**Comment by wokeboy** [comment]
Great suggestions

**Comment by amongX86** [comment]
> Great suggestions
> By the way "End Vote" already kinda exists if you use the vote mod and click skip vote. Instead of actually skipping it just force ends the vote

Yes i know but it sometimes end up voting wrong person which is kinda buggy and ruin the fun. 😕

**Comment by Milionerzy11** [comment]
> > Great suggestions
> > By the way "End Vote" already kinda exists if you use the vote mod and click skip vote. Instead of actually skipping it just force ends the vote
> 
> Yes i know but it sometimes end up voting wrong person which is kinda buggy and ruin the fun. 😕

Yea i aggre it sometimes ruin fun

**Comment by Milionerzy11** [comment]
Also if Devilx86 will add these features then its going to be the best mod in the world ever

**Comment by Devilx86** [comment]
Hello, Good suggestions but I cannot promise all of these for the next update, Because this would delay the update and a lot of people have issues installing/running the app on some devices, which I have fixed. So all you can expect in v1.3 is Bug fixes and about 3 to 4 new features that I made and a couple of awesome features Rev contributed from his mod menu for arm-v7a, I have ported them all to arm64. One of them is actually  move in meeting which I chose to add as a passive feature since I do no want to waste space by adding a toggle switch in the menu. But every time you are in a meeting you should be able to move. I will work on the rest for v1.4.

**Comment by amongX86** [comment]
@Devilx86 Hey, thanks for replying!
 I'll wait for version v1.4 hope you could be able to implement all of them.
By the way i forwarded your project to Axey hope they use and make something out of it.

**Comment by Milionerzy11** [comment]
> Thanks!, Good suggestions but I cannot promise all of these for the next update, Because this would delay the update and a lot of people have issues installing/running the app on some devices, which I have fixed. So all you can expect in v1.3 is Bug fixes and about 3 to 4 new features that I made and a couple of awesome features Rev contributed from his mod menu for arm-v7a, I have ported them all to arm64. One of them is actually move in meeting which I chose to add as a passive feature since I do no want to waste space by adding a toggle switch in the menu. But every time you are in a meeting you should be able to move. I will work on the rest for v1.4.

It will break fun because if you will have mod move in meeting passive then you cant vote if you cant vote then they will kick you from the game

**Comment by Devilx86** [comment]
This is not the case, the way we have done it allows you to move during a meeting as well as vote ;) hence it will stay as a passive feature.

**Comment by wokeboy** [comment]
> This is not the case, the way we have done it allows you to move during a meeting as well as vote ;) hence it will stay as a passive feature.

That's exciting, I can't wait for the update

Any chance it'll be released today? If not, no rush

**Comment by Milionerzy11** [comment]
@amongX86 you can close this by clicking close
